version: '3'

services:
  proz-notifications-app:
    container_name: frontend
    build:
      context: ./www/frontend
      dockerfile: dev.Dockerfile
    env_file: .env
    volumes:
      - ./www/frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - proz-notifications-api

  proz-notifications-api:
    container_name: proz-notifications
    build:
      context: ./www/backend
      dockerfile: dev.Dockerfile
    env_file: .env
    volumes:
      - ./www/backend:/usr/src/server
      - /usr/src/server/node_modules
    ports:
      - "3333:3333"