version: '3'

services:
  next-app:
    container_name: frontend
    build:
      context: ./www/frontend
      dockerfile: dev.Dockerfile
    env_file: .env
    volumes:
      - ./www/frontend:/app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - nestjs-api

  nestjs-api:
    image: nestjs-api
    build:
      context: ./www/backend
      dockerfile: dev.Dockerfile
    env_file: .env
    volumes:
      - ./www/backend:/server
    ports:
      - "3333:3333"